/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListCard: typeof import('./src/components/ListCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    VanCard: typeof import('vant/es')['Card']
    VanKeleton: typeof import('vant/es')['Keleton']
    VanSearch: typeof import('vant/es')['Search']
    VanSeerch: typeof import('vant/es')['Seerch']
    VanSkeleton: typeof import('vant/es')['Skeleton']
  }
}
